# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 579cf6a0efdfc8666c3fe46eace91e096f404d16f8e6102afdc60d80d72f3a32cc02c910d884ff355d18da99447d441dcd067f847164f7f577d9351e73d242ad

test:
  secret_key_base: 6f009dd9a1997dc37303a74a3e7cd55b6fc59915ca5e728ec974e0e247d333f9dd8c55ade6cee6b97c713e0053e327bc5a4d3d2efbb85d5a626fd6136531770c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
